### ISSUE TITLE
Dynamically reload bot

### ISSUE THREAD

**Issue by nickmartini** [cinchrb/cinch#15]
Is there a built-in way to reload the bot (without having to kill the ruby process and start a new one)? I'd like to test my code, but I'm getting klined due to rapid reconnects. Not ideal.

**Comment by bazzinotti** [comment]
@dominikh is your gist still applicable? There is a `Fixme` section I am hoping you can elaborate on how to solve.

**Comment by dominikh** [comment]
The gist is still applicable and the latest version. The fixme refers to the fact that plugin options in Cinch are represented in a hash, mapping classes to options. Deleting the class and creating a completely new one would break that mapping (plugins would lose their configuration). The downsides (not removing methods, not being able to change the superclass) don't usually come up a lot in practice, in my experience.

Personally, I have long switched to a different model, where something like znc proxies the bot, allowing you to restart the bot without users noticing. It's a far simpler approach.
