### ISSUE TITLE
Nickname blacklist/facilities for blacklist management?

### ISSUE THREAD

**Issue by woodruffw** [cinchrb/cinch#199]
Hello there,

Would built-in blacklists or some kind of facility for blacklisting users be within Cinch's scope?

With its current design, implementing a blacklist in a Cinch bot either requires a monkey patch or extensive boilerplate (checking against a set of nicks/hosts in each plug-in). 
I could implement something like this if you think it would be useful.

Best,
William Woodruff

**Comment by green-big-frog** [comment]
+1 for the "idea"

**Comment by jhass** [comment]
Essentially a duplicate of #78

**Comment by woodruffw** [comment]
Oops, should have read through the earlier PRs. 
I'll close this.
