### ISSUE TITLE
When joining a channel, wait for nickserv to identify before sending join commands.

### ISSUE THREAD

**Issue by alfiepates** [cinchrb/cinch#204]
On some networks, you need to be authenticated with nickserv before joining channels is allowed. Cinch fires the `join` command as soon as it connects to the server, which rejects the join request as nickserv hasn't had the opportunity to respond yet. 

Cinch should have an option to wait for nickserv to confirm identification.

**Comment by dominikh** [comment]
Use the `cinch-identify` plugin to identify with nickserv. In your bot's configure block, set `c.delay_joins = :identified`. Cinch will wait for the `:identified` event to fire before joining channels.
