### ISSUE TITLE
Authname support for more than Freenode and Quakenet

### ISSUE THREAD

**Issue by elifoster** [cinchrb/cinch#208]
When a user is not authenticated, their authname value is not nil, as it logically should be. Instead, it is an exclamation point in a string.

**Comment by elifoster** [comment]
I just looked more into the code, turns out it's just because I'm not using Quakenet for Freenode.

**Comment by dominikh** [comment]
If `#authname` returns `"!"`, the server told us that that's the name. What IRC network are you testing this on, and what's the name of an authenticated user on that network>

**Comment by elifoster** [comment]
I am testing on EsperNet. An example authenticated user is "SatanicSanta".

**Comment by dominikh** [comment]
I cannot reproduce the issue. For unauthenticated users, the authname is nil. For authenticated users, it is set correctly. Both WHOIS and WHO output look at expected 

Can you provide a minimal example demonstrating the issue, and include the raw IRC log as printed by Cinch?

**Comment by elifoster** [comment]
Nevermind, it was a minor issue on my end that I didn't see initially.
