### ISSUE TITLE
Messages sent by bot do not fire a channel event

### ISSUE THREAD

**Issue by elifoster** [cinchrb/cinch#214]
It seems that messages sent by the bot do not fire the `:channel` event. Is there a different event just for messages sent by the bot itself? Looking at the log it should be firing, since it recognizes the message as a PRIVMSG.

**Comment by elifoster** [comment]
I just ran a little test using a plugin that says a random word in the channel using `Message#reply`, and a plugin to repeat what is said in the channel using `Message#reply` on a channel event. It only repeated the command message (in this case $randword), not the actual random word.

**Comment by dominikh** [comment]
Messages sent by the bot do not trigger events, and that is by design. Events are for incoming messages. Messages (as in PRIVMSG or NOTICE) that a client sends to the server are not sent back to the client, so there is no incoming message.

If you want your bot to react to its own messages (which, by the way, is an easy way of getting stuck in an infinite loop until the server admin bans you), you will have to do that explicitly. Cinch will not do that for you.

**Comment by elifoster** [comment]
The infinite loop thing is a good point, but that is only something to worry about if you are sending messages back to the server on the message events, and don't have proper checks for whether the message is being duplicated, or if it was the bot's own message.

Anyway, is there some simple way to fire events manually? I can't really find anything in the docs or the code that explicitly shows how that can be done.

**Comment by dominikh** [comment]
> but that is only something to worry about if you are sending messages back to the server on the message events, and don't have proper checks for whether the message is being duplicated, or if it was the bot's own message

That would describe roughly every IRC (and other protocol) bot ever written. Reacting to your own messages is highly atypical.

> is there some simple way to fire events manually?

You can create events synthetically by using `HandlerList#dispatch` (and `Bot#handlers` to get to the `HandlerList`). However, a much simpler approach would be to simply call a method: `process(the_stuff_im_sending)` in your specific message-sending handler that also wants some additional processing done on the message.

There should really never be a reason for a bot to react to its own messages.

**Comment by elifoster** [comment]
>However, a much simpler approach would be to simply call a method: `process(the_stuff_im_sending)` in your specific message-sending handler that also wants some additional processing done on the message.

That was what I was thinking of doing, but I figured I'd create the issue in case it was not by design.

>There should really never be a reason for a bot to react to its own messages.

See [Quintus' logger](https://github.com/Quintus/cinch-plugins/blob/master/plugins/logging.rb), or any other logger that looks similarly to this (not using the actual Logger stuff). Since it uses events rather than the Logger things provided by Cinch, it doesn't log the bots messages.

**Comment by dominikh** [comment]
But that logger could be implemented with the Logger interface. It would be in a rather roundabout way, as it'd need to parse the message again to check whether it was a public message and to access the attributes, but it would still be a more robust solution than the current one.

That is, a possible Logger implementation would overwrite `log`, drop all events that aren't `:incoming` or `:outgoing`, then construct `Message` objects via `Message.new` for the log messages.
