### ISSUE TITLE
Handle netsplits / nickserv renames

### ISSUE THREAD

**Issue by robbat2** [cinchrb/cinch#215]
After netsplits & other events where nickserv renames the bot, it can get lost (it's still running, but not in the expected channels or still identified).

It should automatically handle these cases (eg detect that nick has been changed externally, and after a sleep, trigger /nick + /identify + /join).

**Comment by dominikh** [comment]
That sounds like something that should go in a plugin. Neither keeping its nick, nor identifying to services are core features of Cinch as is, and different networks have vastly different netsplit behaviours and services.

Also, the bot shouldn't "get lost". It will know its new nick, and it will know which channels it is in, unless the IRCd has broken behaviour on netsplits, in which case we can't do anything.

This isn't something Cinch will provide by itself. Write a plugin :)
