### ISSUE TITLE
Run plugins only in certain channels?

### ISSUE THREAD

**Issue by bazzinotti** [cinchrb/cinch#219]
I was just wondering if this functionality is provided or what the best strategy is to incorporate it.
What do you think?

**Comment by txdv** [comment]
Something which runs before every command and checks if some condition is met for the following hooks to be executed?

**Comment by bazzinotti** [comment]
Sounds about right

**Comment by bazzinotti** [comment]
Is there a "global" hook functionality??

If there is no "global" hook functionality, I was thinking of writing high-level code that adds a "pre" hook to every plugin.

**Comment by dominikh** [comment]
See https://github.com/dominikh/Mathetes/blob/cinch_rewrite/bot.rb#L3 and https://github.com/dominikh/Mathetes/blob/cinch_rewrite/lib/cinch/plugins/ideone.rb#L8 for inspiration.

**Comment by bazzinotti** [comment]
Thanks for that! What do you think - keep this an externally implemented feature, or should it be made possible in cinch itself?

**Comment by dominikh** [comment]
Cinch provides hooks. Specific uses of hooks, such as ACLs, should not be part of Cinch.

**Comment by bazzinotti** [comment]
that's not exactly what I meant .. I can't use your solution either because
it requires adding code into the plugins. I'm creating a solution that does
not require editing individual plugin code, and will also allow
plugin-specific hooks to function after the "global" hook.

So I'm looking into how I can "prepend" a pre hook to every plugin. I can
figure it out.

I just thought this kind of thing I am learning to do is different from
"Cinch provides hooks" because Cinch provides hooks only at the plugin
level but I am implementing a higher-level "global pre-hook" I thought
would be useful to others as a public Cinch API rather than having to
implement foreign code.

Let me create a solution first and we can take a closer look at it later.

On Tue, Apr 26, 2016 at 10:38 PM, Dominik Honnef <notifications@github.com>
wrote:

> Cinch provides hooks. Specific uses of hooks, such as ACLs, should not be
> part of Cinch.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cinchrb/cinch/issues/219#issuecomment-214953271>
>



-- 
*****************************
Michael Bazzinotti
​Technologist & Musician​
​
http://www.bazz1.com

[image: Attleboro-low rez] <http://locations.schoolofrock.com/attleboro>
http://locations.schoolofrock.com/attleboro

**Comment by dominikh** [comment]
You can either go the non-magic route and include a module in every plugin as I am doing, or you can monkeypatch the Plugin module and add the hook. That way, all plugins will automatically have it. Either way, Cinch is in maintenance mode and I am unlikely to be adding any major new APIs.

**Comment by bazzinotti** [comment]
Without revealing my config file format (example file is outdated), here is how I did it 😃 
https://github.com/bazzinotti/ayumi/blob/a74f5281db779f03a6e329a1fae6f69f5235e41d/bin/ayumi#L27-L43 and https://github.com/bazzinotti/ayumi/blob/a74f5281db779f03a6e329a1fae6f69f5235e41d/bin/ayumi#L76-L87
