### ISSUE TITLE
How to send "/me" message?

### ISSUE THREAD

**Issue by bazzinotti** [cinchrb/cinch#221]
I am having trouble learning how to do this. Thanks in advance

**Comment by bazzinotti** [comment]
I think I found it. `action_reply`?

**Comment by petertseng** [comment]
Yes, you are correct that http://www.rubydoc.info/gems/cinch/Cinch/Message#action_reply-instance_method can work. There is also http://www.rubydoc.info/gems/cinch/Cinch/Target#action-instance_method so you can do `Channel('#test').action('waves')` or `User('joe').action('waves')` and the bot will wave in-channel or in PM to that user.

**Comment by bazzinotti** [comment]
Thank you!
