### ISSUE TITLE
[example] join_part.rb uses foreign admin functions

### ISSUE THREAD

**Issue by bazzinotti** [cinchrb/cinch#223]
`examples/basic/join_part.rb` is probably from [snap](https://github.com/davidcelis/snap/blob/master/lib/snap/bot.rb#L53-L60)
This code relies at least on an extension of `Cinch::Bot` such as the following:

```
class Bot < Cinch::Bot
  def admins
    @admins ||= $config["irc"]['admins']  # an array of strings
  end

  def admin?(user)
    user.refresh
    admins.include?(user.authname)
  end
end
```

I'm not sure if this is properly documented.

**Comment by petertseng** [comment]
Every function used in https://github.com/cinchrb/cinch/blob/master/examples/basic/join_part.rb seems to be defined - was there a specific one in mind? `is_admin?` is defined [on line 14](https://github.com/cinchrb/cinch/blob/master/examples/basic/join_part.rb#L14), `$admin` is defined [on line 4](https://github.com/cinchrb/cinch/blob/master/examples/basic/join_part.rb#L4), anything else that is missing?

**Comment by bazzinotti** [comment]
No, I got confused. Man, I'm a little embarrassed! Although I will say I like that the one `snap` has uses authname ^_^
