### ISSUE TITLE
Best way to delay sending a response?

### ISSUE THREAD

**Issue by bazzinotti** [cinchrb/cinch#225]
If I want to "queue" something for the bot to write (it's in an event handler), say maybe 1 second delay, is there an API for that? Or should I manually handle this somehow?

Using a "timer-hook" seems a little bit much

**Comment by dominikh** [comment]
Just sleep? Each handler invocation runs in its own thread, so sleeping in a handler won't impact the processing of other messages. If you want to continue in the same handler after queuing, queue in a new thread.

**Comment by bazzinotti** [comment]
thanks dom
