### ISSUE TITLE
Doc page seems down

### ISSUE THREAD

**Issue by TheNotary** [cinchrb/cinch#228]
http://www.rubydoc.info/github/cinchrb/cinch/

I'm getting an error:
```
Sorry, but we couldn't find the page /github/cinchrb/cinch/ in the cinchrb/cinch GitHub repository. Are you sure that class, method, or file exists?
```

Edit:  Oh the borken link I posted was discovered in the gh repo summary/ description.  It looks like it needs to be changed with this `http://www.rubydoc.info/gems/cinch`?

**Comment by dominikh** [comment]
The URL is correct, but for some reason, rubydoc.info has dropped our repository, and refuses to import it again. I'll change it to the URL for the gem like you suggested. Let's hope they don't break that as well. Thanks.
