### ISSUE TITLE
Question: multiple servers

### ISSUE THREAD

**Issue by Fryguy** [cinchrb/cinch#233]
I'm curious if multiple servers can be monitored at the same time by the same bot.  Or, alternately, if multiple bots can run in the same process.

I'm asking because one thing I am trying to do is have the IRC bot watch one IRC server, and ping people in a different server when it sees certain messages.  I can't figure out how to do it without this ability (that is, without resorting to offloading the work to a backend job processor, or some other complicated thing).

I know there's an old issue #29 that talks more about multiple bot instances, but that was 5 years ago, so I'm not sure it's still relevant.

**Comment by dominikh** [comment]
> I'm curious if multiple servers can be monitored at the same time by the same bot

No. A single Bot instance can only connect to a single server.

> Or, alternately, if multiple bots can run in the same process

Normal Ruby applies. Run each Bot#start in its own thread and you can have as many bots, web servers and missile launchers in the same process as you want.

**Comment by Fryguy** [comment]
Thanks @dominikh!  I wasn't sure if it was thread safe or not.  Glad to hear I can make the bot launch my missiles 🚀  😄
