### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lokeshh** [cinchrb/cinch#242]
This is a great app but it seems most of the plugins and examples are not working.

**Comment by dominikh** [comment]
It's not really maintained, no. Though to the best of my knowledge, there are no critical bugs, and most of the examples, and really the majority of 1st and 3rd party plugins are working fine. The google example is probably broken, as they change their markup every other day, and including the example was a mistake.

Long story short, Cinch is perfectly usable, but we are looking for an active maintainer who wants to fix outstanding issues and PRs and maybe clean up the code some.

**Comment by IotaSpencer** [comment]
I'd love to help, I'm working on cinch every day

**Comment by bougyman** [comment]
It is now maintained again, @IotaSpencer . I would very much appreciate any help you can offer. I'm just looking through issues now and will start to tag them with priorities. You can always find me on freenode (#cinch)
