### ISSUE TITLE
backup file in gem

### ISSUE THREAD

**Issue by mschnitzer** [cinchrb/cinch#252]
Hi,

I'm about to package your gem for openSUSE so that people can install it via our package manager. While packaging, I received the following error:

```
ruby2.4-rubygem-cinch.x86_64: E: suse-filelist-forbidden-backup-file (Badness: 10000) /usr/lib64/ruby/gems/2.4.0/gems/cinch-2.3.3/lib/cinch/version.rb~ is not allowed in SUSE
```

It seems that you accidentally put a backup file from MacOS in the gem file. Can you please double check and maybe get rid of it? I think it shouldn't be in the gem file, right?

**Comment by dominikh** [comment]
Should be fixed in v2.3.4

Maybe @bougyman can fix the build process one day.

P.S.: not an macOS file, but zile/emacs

**Comment by mschnitzer** [comment]
@dominikh thanks!

**Comment by bougyman** [comment]
Build process is on top of my list, now. Thanks Dominik.
Tj
