### ISSUE TITLE
Mismatch between code and released version.

### ISSUE THREAD

**Issue by duckinator** [cinchrb/cinch#258]
The last-released version of Cinch, [as can be seen on rubygems.org](https://rubygems.org/gems/cinch), is v2.3.4.

If you go to the [v2.3.4 tag](https://github.com/cinchrb/cinch/releases/tag/v2.3.4), there is a [commit that bumps the version to v2.3.4](https://github.com/cinchrb/cinch/commit/1156edbd2f54e6422827432f09929e7809c90c44).

Yet, somehow, both [the gemspec](https://github.com/cinchrb/cinch/blob/master/cinch.gemspec) and [`version.rb`](https://github.com/cinchrb/cinch/blob/master/lib/cinch/version.rb) on the master branch list the version as v2.3.1.

It appears that code never made it to the master branch.

**Comment by dominikh** [comment]
These versions were cut from the, nowadays deleted, maint branch. The version number on the master branch is currently out of sync; all the changes that went into 2.3.4 are, however, present in master.
