### ISSUE TITLE
idle method always return 0

### ISSUE THREAD

**Issue by noraj** [cinchrb/cinch#262]
`m.user.idle` is always equal to `0` for users even if I use `bot.irc.send "WHOIS #{m.user.nick}"` just before.

https://github.com/cinchrb/cinch/blob/c66bbe7805426ed0053d52550f134b0a66f42c93/lib/cinch/irc.rb#L666-L680

On the debug output of the bot I can see the logger is viewing `0`.

![](https://i.imgur.com/vrNUojW.png)

But when I used the IRC command `/WHOIS user` I can see the idle time is not zero.

**Comment by noraj** [comment]
I tried using `m.user.refresh`

> Queries the IRC server for information on the user. This will set the User’s state to not synced. After all information are received, the object will be set back to synced.

and also `m.user.monitor`

> Starts monitoring a user’s online state by either using MONITOR or periodically running WHOIS.

before using `m.user.idle` but that's still returning zero.

**Comment by noraj** [comment]
Is that not because when using `#idle` this is calling an underlying `PING` command toward the user? So this is resetting the user idle time (inspircd behavior).

![](https://i.imgur.com/aB3OXYn.png)

**Comment by dominikh** [comment]
We're not PINGing the user.

**Comment by noraj** [comment]
It is very easy to reproduce.

Create a bot joining an inspircd server using this block:

```ruby
  on :private, /^!test$/ do |m|
    m.reply m.user.idle.to_s
  end
```

Then send a private message `!test` to the bot, the user will always receive zero.

**Comment by dominikh** [comment]
Of course the user will get a zero idle time. He literally just sent a message to the bot. He's not idle.

**Comment by noraj** [comment]
@dominikh I restarted the server and now and now it is behaving like you said: idle time is the because the user just sent a message. Of course I'm dumb. But that's weird that the `WHOIS` command was returning me an idle time of several minutes just after the user send a message, now I tried again and this is not doing it anymore.

**Comment by noraj** [comment]
@dominikh How can I get an synced version of idle instead of having the result of the last WHOIS? Do I need to call `#refresh` before?

**Comment by dominikh** [comment]
> Do I need to call #refresh before?

Yes.
